# Generated by Django 4.2.11 on 2024-06-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0045_fileobject"),
    ]

    operations = [
        migrations.AddField(
            model_name="KITuser",
            name="email_verification_code",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="KITuser",
            name="verified_email",
            field=models.BooleanField(default=False),
        ),
    ]
